posta/urls.py
from django.conf.urls import patterns, url
from posta import views

urlpatterns = patterns(' ',
    url(r'^$', views.index, name='posta.index'),
    url(r'^about/', views.about, name='posta.about'),
    url(r'^schedule/', views.schedule, name='posta.schedule'),
    url(r'^mail/$', views.mail, name='posta.mail'),
    url(r'^mail/create/$', views.mail_create, name='posta.mail.create'),
    url(r'^mail/edit/(?P<mail_id>\w+)/$', views.mail_edit, name='posta.mail.edit'),
    url(r'^mail/preview/(?P<mail_id>\w+)/$', views.mail_preview, name='posta.mail.preview')
)

posta_lobo_project/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic.base import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'posta_lobo_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^users/', RedirectView.as_view(url='/')),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('posta.urls')),

    )

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root':settings.MEDIA_ROOT}),)

posta/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Mail(models.Model):
    DRAFT = 0
    READY = 1
    SENT = 2
    STATUS_CHOICES= ((DRAFT, 'Draft'),(READY, 'Ready'), (SENT, 'Sent'))
    name = models.CharField(max_length=140, unique=True)
    date_created = models.DateTimeField(auto_now=True)
    date_scheduled = models.DateField()
    target = models.CharField(max_length=140)
    template = models.ForeignKey('mail_template')
    subject_line = models.CharField(max_length=140)
    headline = models.CharField(max_length=140)
    mail_body = models.TextField()
    status = models.IntegerField(choices=STATUS_CHOICES, default=DRAFT)
    image = models.URLField(null=True)
    created_by = models.ForeignKey(User)
    button_url = models.TextField(null=True)
    
    def __unicode__(self):
        return self.name


#TODO: Rename to MailTemplate
class mail_template(models.Model):
    name = models.TextField()
    template_body = models.TextField()
    
    def __unicode__(self):
        return self.name

posta/forms.py
from django import forms
from posta.models import Mail, mail_template
from django.contrib.auth.models import User

class MailForm(forms.ModelForm):
    name = forms.CharField(max_length=140, help_text="Please enter a name for your email.")
    subject_line = forms.CharField(max_length=140, help_text="Please enter the subject line for your email.")
    target = forms.CharField(max_length=140, help_text="Who is this email going to?")
    date_scheduled = forms.DateField(help_text="When do you need this email sent?",
                                     widget=forms.TextInput(attrs={'id':'datepicker'}))    
    template = forms.ModelChoiceField(queryset=mail_template.objects.all(), help_text="Select a Template", widget=forms.RadioSelect)
    headline = forms.CharField(max_length=140, help_text="Please enter a headline for your email.")
    mail_body = forms.CharField(widget=forms.Textarea)
    image = forms.CharField(widget=forms.TextInput)
    button_url = forms.URLField()
    
    class Meta:
        model = Mail
        fields = ('name','subject_line','target','date_scheduled','template', 'headline', 'image', 'mail_body')
        #You can use widgets in the metafield. Look it up!


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password')        

posta/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from posta.forms import MailForm
from django.shortcuts import render_to_response, get_object_or_404
from django.template import *
from django.template.loader import *
from django.contrib.auth.decorators import login_required
from posta.models import *
from django.contrib.formtools.preview import FormPreview
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
import sendgrid

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def schedule(request):
    context = RequestContext(request)
    #Pass Current Emails to Template
    all_mail = Mail.objects.all()
    context_dict = {'emails' : all_mail } 
    for mail in all_mail:    
        mail.url = mail.id  
    return render_to_response('schedule.html', context_dict, context)

@login_required
def mail(request):
    context = RequestContext(request)
    all_mail = Mail.objects.all()
    context_dict = {'emails' : all_mail } 
    for mail in all_mail:    
        mail.url = mail.id
    return render_to_response('mail.html', context_dict, context)

  
@login_required
def mail_create(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = MailForm(data=request.POST)
        if form.is_valid():
          if 'preview' in request.POST:
              email = form.save(commit=False)
              template_body = form.cleaned_data['template'].template_body
              template = Template(template_body)
              return HttpResponse(template.render(Context({'mail':email})))
          elif 'save' in request.POST:
              email = form.save(commit=False)
              email.created_by = request.user
              email.save()
              
              template_body = form.cleaned_data['template'].template_body
              template = Template(template_body)
              #HTML Sends the String of Template + Form Data as Attachment
              html = template.render(Context({'mail':email}))
              
              sg = sendgrid.SendGridClient('ishfuseini', 'XXXXX')
              #Email - https://github.com/sendgrid/sendgrid-python#example
              message = sendgrid.Mail()
              message.add_to(['a@a.com'])
              message.set_subject('Example')
              message.set_html("Dear Brah or Brahette: Here's your email.")
              message.set_from('Posta Mail App <posta@email.com>')
              message.add_attachment_stream('your_email.html', html) #not sure if this will work
              status, msg = sg.send(message)
              
              #TODO: What if there's an error? (ie status != 200)
              
              print status
              print msg
              if status == 200:
                email.status = Mail.DRAFT
                email.save()

              return HttpResponseRedirect(reverse('posta.mail'))
        else:
            print form.errors
    else:
        form = MailForm()
    return render_to_response('create_test.html', {'form' : form}, context)



  
@login_required
def mail_edit(request, mail_id):
    #TODO: Right now anybody can edit any mail
    #      Make is so you can only edit your own!
    context = RequestContext(request)
    mail = get_object_or_404(Mail, pk=mail_id)
    if mail.created_by != request.user:
        return HttpResponseRedirect(reverse('posta.index'))
    context_dict = {} 
    context_dict['mail'] = mail        
    if request.method == 'POST':       
        form = MailForm(request.POST, instance=mail)        
        if form.is_valid():
            form.save(commit=True)            
            return HttpResponseRedirect(reverse('posta.mail'))
        else:
            print form.errors
    else:
        form = MailForm(instance=mail)
        context_dict['form'] = form        
    return render_to_response('mail_edit.html', context_dict, context)
  
@login_required
def mail_preview(request, mail_id):
    mail = get_object_or_404(Mail, pk=mail_id)
    subject_line =  mail.subject_line
    headline = mail.headline
    mail_body = mail.mail_body
    image = mail.image
    context_dict = {'mail' : mail} 
    context_dict['subject_line'] = subject_line
    context_dict['headline'] = headline
    context_dict['mail_body'] = mail_body
    context_dict['image'] = image 
    t = Template(mail.template.template_body)
    preview = t.render(Context(context_dict))
    return HttpResponse(preview)
  

grappelli/tinymce/examples/templates/layout1.htm
<table border="1">
	<thead>
		<tr>
			<td>Column 1</td>
			<td>Column 2</td>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>Username: {$username}</td>
			<td>Staffid: {$staffid}</td>
		</tr>
	</tbody>
</table>

grappelli/tinymce/examples/templates/snippet1.htm
This is just some <strong>code</strong>.

templates/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock %}
{% block headline %} About Posta {% endblock %}
{% block body_block %}

<div class="page-header">
  <h1>What is posta? <br> <small>Posta is a tool that allows you to create an email quickly to send to your clients. </small></h1>
</div>



{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Ish Fuseini">

    <title>Posta - {% block title %} {% endblock %} </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/sticky-footer-navbar.css" %}" rel="stylesheet">
    <link href="{% static "css/image-picker.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script>
        tinymce.init({selector:'textarea'});
</script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/image-picker.min.js" %}"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
  
<script>
  $(function() {
    $( "#datepicker" ).datepicker({
      changeMonth: true,
      minDate: +2,
    });
  });
  </script>
  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Posta</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="{% url "posta.about" %}">About</a></li>
            <li><a href="{% url "posta.schedule" %}">Schedule</a></li>
            <li><a href="{% url "posta.mail" %}">Mail</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          
            {% if user.is_authenticated %}
            <li><a href="/accounts/logout">Logout</a></li>
            {% else %}
            <li><a href="/accounts/register">Register</a></li>
            <li><a href="/accounts/login">Login</a></li>
            {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- Begin page content -->
    <div class="container">
      <div class="page-header">
        <h1>  {% block headline %} {% endblock %}</h1>
      </div>
     {% block body_block %} {% endblock %}
    </div>

    <div id="footer">
      <div class="container">
        <p class="text-muted">Created by Ish Fuseini </p>
      </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->



  </body>
</html>

templates/create.html
{% extends 'base.html' %}

{% block title %} Edit {% endblock %}
{% block headline %} Edit {{ mail.name }}  {% endblock %}
{% block body_block %}

<div class="page-header">
 
  <form id="mail_form" method="post" action="/mail/create/">
  {% csrf_token %}

  {{ form.as_p}}



  <input type="submit" name="submit" value="Create Mail" />
  </form>
  
  
</div>



{% endblock %}

templates/create_test.html
{% extends 'base.html' %}

{% block title %} Edit {% endblock %}
{% block headline %} Create {{ mail.name }}  {% endblock %}
{% block body_block %}

<div class="page-header">




    <form id="mail_form" method="post" action="/mail/create/" class="form-horizontal">
      {% csrf_token %}
      
      
      <p class="bg-danger">
      
      


      </p>

<fieldset>
<!-- Name-->
<div class="control-group">
  <label class="control-label" for="name">Name:</label>
  <div class="controls">
    <input id="name" name="name" type="text" placeholder="Email Name" class="input-xlarge">
    <p class="help-block">Please enter a name for your email.</p>
    <p class="bg-danger">{{ form.name.errors }}</p>
  </div>
</div>

<!-- Subject Line-->
<div class="control-group">
  <label class="control-label" for="subject_line">Subject Line:</label>
  <div class="controls">
    <input id="subject_line" name="subject_line" type="text" placeholder="" class="input-xlarge">
    <p class="help-block">Please enter the subject line for your email</p>
        <p class="bg-danger">{{ form.subject_line.errors }}</p>
  </div>
</div>
  
  <!-- Head Line-->
<div class="control-group">
  <label class="control-label" for="headline">Headline:</label>
  <div class="controls">
    <input id="headline" name="headline" type="text" placeholder="" class="input-xlarge">
    <p class="help-block">Title/Headline</p>
      <p class="bg-danger">{{ form.headline.errors }}</p>
  </div>
</div>

<!-- Target  -->
<div class="control-group">
  <label class="control-label" for="target">Target:</label>
  <div class="controls">
    <select id="target" name="target" class="input-xlarge" multiple="multiple">
      <option>Wolves STM</option>
      <option>Lynx STM</option>
      <option>WolvesOffers</option>
      <option>LynxOffers</option>
      <option>Target Center Events</option>
      <option>Account Executive</option>
    </select>
  </div>
    <p class="bg-danger">{{ form.target.errors }}</p>
</div>

<!-- Date Scheduled -->
<div class="control-group">
  <label class="control-label" for="date_scheduled">Date scheduled:</label>
  <div class="controls">
    <input id="datepicker" name="date_scheduled" type="text" placeholder="MM/DD/YY" class="input-xlarge">
    <p class="help-block">When do you need this email sent?</p>
  </div>
  <p class="bg-danger">{{ form.date_scheduled.errors }}</p>
</div>

<!-- Template Select -->
<div class="control-group">

  <div class="controls">
<p>
<ul id="id_template">
<li><label for="id_template_0"><input checked="checked" id="id_template_0" name="template" type="radio" value=""> ---------</label></li>
<li><label for="id_template_1"><input id="id_template_1" name="template" type="radio" value="1"> STM</label></li>
</ul>
  </div>
  <p class="bg-danger">{{ form.template.errors }}</p>
</div>

 <!-- Image -->
<div class="control-group">
  <label class="control-label" for="image">Select An Image</label>
  
 <button class="btn btn-primary btn-lg" type="button" id="modal-button" data-toggle="modal" data-target="#myModal">
  Launch Gallery
 </button>

   
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Gallery</h4>
      </div>
      <div class="modal-body">
    
  <div class="controls">
    <select id="image" name="image" class="input-xlarge image-picker" >
      <option value=""></option>
  <option data-img-src="http://event.wolveslynx.com/rs/minnesotatimberwolves/images/TW_25_INVITED_USB_MB.png" value="http://event.wolveslynx.com/rs/minnesotatimberwolves/images/TW_25_INVITED_USB_MB.png">http://event.wolveslynx.com/rs/minnesotatimberwolves/images/TW_25_INVITED_USB_MB.png</option>
  <option data-img-src="http://event.wolveslynx.com/rs/minnesotatimberwolves/images/TW_25_Member_Info_USB.png" value="http://event.wolveslynx.com/rs/minnesotatimberwolves/images/TW_25_Member_Info_USB.png">Member Info</option>
  <option data-img-src="http://event.wolveslynx.com/rs/minnesotatimberwolves/images/TW_25_R_U_RDY_USB.png" value="http://event.wolveslynx.com/rs/minnesotatimberwolves/images/TW_25_R_U_RDY_USB.png">Are You Ready?</option>
    </select>
  </div>
        

    <p class="bg-danger">{{ form.image.errors }}</p>
</div>
      </div>
      <div class="modal-footer">
       <button class="btn btn-primary btn-lg"   data-dismiss="modal" type="button" >
Close
 </button>
      </div>
    </div>
  </div>
</div>
  
</div>
  
<!-- Mail Body -->
<div class="control-group">
  <label class="control-label" for="mail_body">Mail Body:</label>
  <div class="controls">                     
    <textarea id="mail_body" name="mail_body"></textarea>
  </div>
      <p class="bg-danger">{{ form.mail_body.errors }}</p>
</div>

<!--Button Link-->
<div class="control-group">
  <label class="control-label" for="button_url">Button Link:</label>
  <div class="controls">
    <input id="button_url" name="button_url" type="text" placeholder="http://ishfuseini.com/" class="input-xlarge">
    <p class="help-block">Insert the link for your button</p>
  </div>
      <p class="bg-danger">{{ form.button_url.errors }}</p>
</div>

</fieldset>

  <input type="submit" name="preview" value="Preview Mail" target="_blank" class="btn btn-lg btn-success"/>
  <input type="submit" name="save" value="Create Mail"  class="btn btn-lg btn-primary"/>
  

  </form>
  
</div>

<script type="text/javascript">
     $("#image").imagepicker({
          hide_select : true,
          show_label  : false
        })
     
     //$("#modal-button").click(function(){
       // $("myModal").modal("show");
        //return false;
     //});
      
</script>


{% endblock %}

templates/edit.html
{% extends 'base.html' %}

{% block title %} Edit {% endblock %}
{% block headline %} Edit {{ mail.name }}  {% endblock %}
{% block body_block %}

<div class="page-header">
 
  <form id="mail_form" method="post" action="/mail/">
  {% csrf_token %}

  {{ form.as_p}}



  <input type="submit" name="submit" value="Create Mail" />
  </form>
  
  
</div>



{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Home {% endblock %}
{% block headline %} Let's Create an Email {% endblock %}
{% block body_block %}

<a type="button" class="btn btn-primary" href="{% url "posta.mail" %}"> Create an Email </a>

{% endblock %}

templates/mail.html
{% extends 'base.html' %}

{% block title %} Mail {% endblock %}
{% block headline %} Mail {% endblock %}
{% block body_block %}

<div class="page-header">

  <table class="table">
    <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Subject Line</th>
          <th>Date Scheduled</th>
          <th>Status</th>
        </tr>
      </thead>
        {% if emails %}
    {% for mail in emails %}
    <tr>
    	<td>
    		<a href="/mail/edit/{{ mail.url }}">{{ mail.id }}</a>
    	</td>

      <td>
      	   {{ mail.name }}
      </td>
           
 <td>
           {{ mail.subject_line }}
      </td>

      <td>
           {{ mail.date_scheduled }}
      </td>
      <td>
      	   {{ mail.get_status_display }}
      </td>
      
     
      
     
     
     
            

    </tr>
       {% endfor %}
{% endif %}
   
  </table>



  
<a type="button" class="btn btn-primary" href="{% url "posta.mail.create" %}"> Create an Email </a>
  
</div>



{% endblock %}

templates/mail_create.html
{% extends 'base.html' %}

{% block title %} Edit {% endblock %}
{% block headline %} Create {{ mail.name }}  {% endblock %}
{% block body_block %}

<div class="page-header">
 
  <form id="mail_form" method="post" action="/mail/create/">
  {% csrf_token %}

  {{ form.as_p}}

  <input type="submit" name="preview" value="Preview Mail" target="_blank" class="btn btn-lg btn-success"/>
  <input type="submit" name="save" value="Create Mail"  class="btn btn-lg btn-primary"/>
  

  </form>
  
</div>



{% endblock %}

templates/mail_edit.html
{% extends 'base.html' %}

{% block title %} Edit {% endblock %}
{% block headline %} Edit {{ mail.name }}  {% endblock %}
{% block body_block %}

<div class="page-header">
 
  <form id="mail_form" method="post" action="{% url 'posta.mail.edit' mail.id %}">
  {% csrf_token %}

  {{ form.as_p}}



    <a href="{% url 'posta.mail.preview' mail.id %}" class="btn btn-lg btn-success"  target="_blank" >Preview Email</a> <input type="submit" name="submit" value="Update Mail"  class="btn btn-lg btn-primary" />
  </form>

  <br>
  

  
</div>



{% endblock %}

templates/schedule.html
{% extends 'base.html' %}

{% block title %} Schedule   {% endblock %}
{% block headline %} Schedule  {% endblock %}
{% block body_block %}

 <script>
$('a.external').on('click', function(e) {
        e.preventDefault();
        var url = $(this).attr('href');
        $(".modal-body").html('<iframe width="100%" height="100%" frameborder="0" scrolling="yes" allowtransparency="true" src="'+url+'"></iframe>');
 
    });
 
    $('#myModal').on('show.bs.modal', function () {
 
        $(this).find('.modal-dialog').css({
                  width:'100%x', //choose your width
                  height:'100%', 
                  'padding':'20'
           });
         $(this).find('.modal-content').css({
                  height:'100%', 
                  'border-radius':'0',
                  'padding':'0'
           });
         $(this).find('.modal-body').css({
                  width:'auto',
                  height:'100%', 
                  'padding':'0'
           });
    })
</script>


<div class="page-header">
  <h1><small>Here are the upcoming campaigns this month </small></h1>

  <table class="table">
    <thead>
        <tr>
          <th>#</th>
          <th>Name</th>

          <th>Date Scheduled</th>
          <th>Status</th>
           <th>Created By</th>
        </tr>
      </thead>
        {% if emails %}
    {% for mail in emails %}
    <tr>
    	<td>
    		<a href="/mail/preview/{{ mail.url }}" class="btn btn-primary btn-xs external" data-toggle="modal" data-target="#myModal">{{ mail.id }}</a>
    	</td>
      <td>
      	   {{ mail.name }}
      </td>         
      <td>
           {{ mail.date_scheduled }}
      </td>
      <td>
      	   {{ mail.get_status_display }}
      </td>
          <td>
      	   {{ mail.created_by }}
      </td>
    </tr>
       {% endfor %}
{% endif %}
   
  </table>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
      </div>
      </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



{% endblock %}